export {SectionOne} from "./Section1"
export {SectionTwo} from "./Section2"
export {SectionThree} from "./Section3"
export {SectionFour} from "./Section4"
export {SectionFive} from "./Section5"
export {SectionSix} from "./Section6"
export {SectionSeven} from "./Section7"